"""Added date and type in contact_us  table

Revision ID: 4c94644cc5d5
Revises: 
Create Date: 2024-05-26 18:01:04.670399

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4c94644cc5d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contact_us_company_name', table_name='contact_us')
    op.drop_index('ix_contact_us_created_at', table_name='contact_us')
    op.drop_index('ix_contact_us_email', table_name='contact_us')
    op.drop_index('ix_contact_us_first_name', table_name='contact_us')
    op.drop_index('ix_contact_us_id', table_name='contact_us')
    op.drop_index('ix_contact_us_last_name', table_name='contact_us')
    op.drop_index('ix_contact_us_message', table_name='contact_us', mysql_length={'message': 768})
    op.drop_index('ix_contact_us_postion', table_name='contact_us')
    op.drop_index('ix_contact_us_servicetype', table_name='contact_us')
    op.drop_table('contact_us')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_us',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('company_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('servicetype', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('position', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('message', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_contact_us_servicetype', 'contact_us', ['servicetype'], unique=False)
    op.create_index('ix_contact_us_postion', 'contact_us', ['position'], unique=False)
    op.create_index('ix_contact_us_message', 'contact_us', ['message'], unique=False, mysql_length={'message': 768})
    op.create_index('ix_contact_us_last_name', 'contact_us', ['last_name'], unique=False)
    op.create_index('ix_contact_us_id', 'contact_us', ['id'], unique=False)
    op.create_index('ix_contact_us_first_name', 'contact_us', ['first_name'], unique=False)
    op.create_index('ix_contact_us_email', 'contact_us', ['email'], unique=False)
    op.create_index('ix_contact_us_created_at', 'contact_us', ['created_at'], unique=False)
    op.create_index('ix_contact_us_company_name', 'contact_us', ['company_name'], unique=False)
    # ### end Alembic commands ###
