"""Added date and type in contact_us table -1

Revision ID: 4f3b8a9a5efc
Revises: 4c94644cc5d5
Create Date: 2024-05-26 18:10:26.894496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f3b8a9a5efc'
down_revision = '4c94644cc5d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
