"""Added contact_us table 2

Revision ID: 9d738d820a9e
Revises: a6d66e0f4efa
Create Date: 2024-05-26 18:27:22.734315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d738d820a9e'
down_revision = 'a6d66e0f4efa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
