"""Added contact_us table -1

Revision ID: a6d66e0f4efa
Revises: 4f3b8a9a5efc
Create Date: 2024-05-26 18:18:40.176347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6d66e0f4efa'
down_revision = '4f3b8a9a5efc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
